trigger: 
- main

pool: Default

# variables: 
#  working_path: $(System.DefaultWorkingDirectory)/environments/dev

stages:
  - stage:
    displayName: Initplan 
    jobs:
      - job: 
        displayName: job terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            backendAzureRmUseEntraIdForAuthentication: false
            backendServiceArm: 'serviceconnection-may'
            backendAzureRmResourceGroupName: 'agent_rg'
            backendAzureRmStorageAccountName: 'satishstorage1122'
            backendAzureRmContainerName: 'containersatish'
            backendAzureRmKey: 'infra-hub-spoke.tfstate'
        - task: TerraformTask@5
          displayName: terraform FMT
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'serviceconnection-may'
        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
        - task: TerraformTask@5
          displayName: terraform plan
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'serviceconnection-may'

  - stage:
    displayName: sacning tools
    jobs:
      - job: 
        displayName: tfsec-checkov
        steps:
        - task: tfsec@1
          continueOnError: true
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/s'
  - stage: 
    displayName: terraform apply
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environments/dev'
            environmentServiceNameAzureRM: 'serviceconnection-may'
        # - task: Bash@3
        #   inputs:
        #     targetType: 'inline'
        #     script: |
        #       echo "Installing required packages..."
              
        #           sudo apt-get update -y
        #           sudo apt-get install -y curl wget unzip git
              
        #           echo "Downloading TFLint install script..."
              
        #           wget https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh
              
        #           chmod +x install_linux.sh
              
        #           echo "Installing TFLint..."
              
        #           ./install_linux.sh
              
        #           export PATH=$PATH:/usr/local/bin
              
        #           echo "Checking TFLint version..."
              
        #           tflint --version
              
        #           echo "======================================"
        #           echo " Creating .tflint.hcl "
        #           echo "======================================"
              
        #           cat <<EOF > .tflint.hcl
        #           plugin "azurerm" {
        #             enabled = true
        #             version = "0.24.0"
        #             source  = "github.com/terraform-linters/tflint-ruleset-azurerm"
        #           }
              
        #           rule "terraform_unused_declarations" {
        #             enabled = true
        #           }
              
        #           rule "terraform_unused_required_providers" {
        #             enabled = true
        #           }
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/s'


