trigger: none

pool: Default

stages:
  - stage:
    displayName: Initplan 
    jobs:
      - job: 
        displayName: job terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: terraform init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'serviceconnection-may'
            backendAzureRmResourceGroupName: 'agent_rg'
            backendAzureRmStorageAccountName: 'satishstorage1122'
            backendAzureRmContainerName: 'containersatish'
            backendAzureRmKey: 'infra-hub-spoke.tfstate'
        - task: TerraformTask@5
          displayName: terraform FMT
          inputs:
            provider: 'azurerm'
            command: 'custom'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'serviceconnection-may'
        - task: TerraformTask@5
          displayName: terraform validate
          inputs:
            provider: 'azurerm'
            command: 'validate'

  - stage:
    displayName: sacning tools
    jobs:
      - job: 
        displayName: tfsec-checkov
        steps:
        - task: tfsec@1
          inputs:
            version: 'v1.26.0'
            dir: '$(System.DefaultWorkingDirectory)/s'


