trigger: none

pool: Default

stages:
  - stage:
    displayName: Initplan 
    jobs:
      - job: 
        displayName: job terraforminit
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)'
            backendServiceArm: 'serviceconnection-may'
            backendAzureRmResourceGroupName: 'agent_rg'
            backendAzureRmStorageAccountName: 'satishstorage1122'
            backendAzureRmContainerName: 'containersatish'
            backendAzureRmKey: 'infra-hub-spoke.tfstate'

